import React from "react";
import Head from "next/head";

const HeaderComponet = () => {
	return (
		<Head>
			<title>Portfolio</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default HeaderComponet;
